disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity
  - type_name
  - trailing_comma
  - inclusive_language

opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - vertical_parameter_alignment_on_call
  - force_cast
  - force_try
  - identifier_name
  - for_where
  - non_optional_string_data_conversion

included:
  - Sources
  - Tests

excluded:
  - .build
  - Package.resolved