#!/bin/bash
set -e

# Resolve directories relative to script location
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERSION_FILE="$SCRIPT_DIR/../VERSION"
OUTPUT_FILE="$SCRIPT_DIR/../Sources/M3U8FalconCLI/Version.swift"

if [ ! -f "$VERSION_FILE" ]; then
    echo "Error: VERSION file not found at $VERSION_FILE" >&2
    exit 1
fi

# Read version and trim whitespace/newlines
VERSION=$(cat "$VERSION_FILE" | tr -d '\n' | tr -d '\r' | xargs)

# Generate Version.swift
cat << EOF > "$OUTPUT_FILE"
//
//  Version.swift
//  M3U8FalconCLI
//
//  Auto-generated by scripts/generate-version.sh. Do not edit.
//

enum CLI {
    static let version = "$VERSION"
}
EOF

echo "✅ Generated Version.swift with version $VERSION"
